name: Publish Plugin

on:
  push:
    branches: ['main']
    paths: ['packages/vite-plugin-webext/**']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Build & Publish package
        working-directory: ./packages/vite-plugin-webext
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
